export * from './geofence';
export * from './calendar';
export * from './reports';
export * from './user';
export const name = "shared-types";
export interface CreateVoterRequest {
    name: string;
    motherName?: string;
    cpf?: string;
    dateOfBirth?: string;
    gender?: 'MASCULINO' | 'FEMININO' | 'OUTRO' | 'NAO_INFORMADO' | string;
    phone?: string;
    whatsapp?: string;
    email?: string;
    address?: string;
    addressNumber?: string;
    addressComplement?: string;
    neighborhood?: string;
    city?: string;
    state?: string;
    zipCode?: string;
    latitude?: number;
    longitude?: number;
    electoralTitle?: string;
    electoralZone?: string;
    electoralSection?: string;
    votingLocation?: string;
    educationLevel?: 'FUNDAMENTAL_INCOMPLETO' | 'FUNDAMENTAL_COMPLETO' | 'MEDIO_INCOMPLETO' | 'MEDIO_COMPLETO' | 'SUPERIOR_INCOMPLETO' | 'SUPERIOR_COMPLETO' | 'POS_GRADUACAO' | 'NAO_INFORMADO' | string;
    occupation?: string;
    incomeLevel?: 'ATE_1_SALARIO' | 'DE_1_A_2_SALARIOS' | 'DE_2_A_5_SALARIOS' | 'DE_5_A_10_SALARIOS' | 'ACIMA_10_SALARIOS' | 'NAO_INFORMADO' | string;
    maritalStatus?: 'SOLTEIRO' | 'CASADO' | 'DIVORCIADO' | 'VIUVO' | 'UNIAO_ESTAVEL' | 'NAO_INFORMADO' | string;
    religion?: string;
    ethnicity?: string;
    facebook?: string;
    instagram?: string;
    twitter?: string;
    supportLevel?: 'MUITO_FAVORAVEL' | 'FAVORAVEL' | 'NEUTRO' | 'DESFAVORAVEL' | 'MUITO_DESFAVORAVEL' | 'NAO_DEFINIDO' | string;
    politicalParty?: string;
    votingHistory?: string;
    topIssues?: string[];
    issuePositions?: Record<string, any>;
    previousCandidateSupport?: string;
    influencerScore?: number;
    persuadability?: string;
    turnoutLikelihood?: 'ALTO' | 'MEDIO' | 'BAIXO' | 'NAO_DEFINIDO' | string;
    familyMembers?: number;
    hasWhatsapp?: boolean;
    preferredContact?: 'TELEFONE' | 'WHATSAPP' | 'EMAIL' | string;
    notes?: string;
    tags?: string[];
    engagementTrend?: 'CRESCENTE' | 'ESTAVEL' | 'DECRESCENTE' | 'NAO_DEFINIDO' | string;
    seasonalActivity?: Record<string, any>;
    lastContactDate?: string;
    contactFrequency?: number;
    responseRate?: number;
    eventAttendance?: string[];
    volunteerStatus?: 'ATIVO' | 'INATIVO' | 'INTERESSADO' | 'NAO_VOLUNTARIO' | string;
    donationHistory?: Record<string, any>[];
    engagementScore?: number;
    ageGroup?: string;
    householdType?: 'SOLTEIRO' | 'FAMILIA_COM_FILHOS' | 'FAMILIA_SEM_FILHOS' | 'IDOSOS' | 'ESTUDANTES' | 'NAO_INFORMADO' | string;
    employmentStatus?: 'EMPREGADO' | 'DESEMPREGADO' | 'APOSENTADO' | 'ESTUDANTE' | 'AUTONOMO' | 'NAO_INFORMADO' | string;
    vehicleOwnership?: boolean;
    internetAccess?: string;
    communicationStyle?: 'FORMAL' | 'INFORMAL' | 'NAO_DEFINIDO' | string;
    contentPreference?: string[];
    bestContactTime?: string;
    bestContactDay?: string[];
    socialMediaFollowers?: number;
    communityRole?: 'LIDER' | 'MEMBRO_ATIVO' | 'ATIVISTA' | 'MEMBRO' | 'NAO_PARTICIPANTE' | 'NAO_DEFINIDO' | string;
    networkSize?: number;
    influenceRadius?: number;
    referralCode?: string;
    referredBy?: string;
    referralDate?: string;
}
