import type { SavedReport } from "@/types/reports";

export const savedReports: SavedReport[] = [
  {
    id: "1",
    name: "Eleitores Engajados de São Paulo",
    description: "Eleitores com alto engajamento na cidade de São Paulo",
    filters: [
      {
        id: "f1",
        field: "city",
        operator: "equals",
        value: "São Paulo",
        logicalOperator: "AND",
      },
      {
        id: "f2",
        field: "engagementScore",
        operator: "greaterThan",
        value: 70,
        logicalOperator: "AND",
      },
      {
        id: "f3",
        field: "supportLevel",
        operator: "in",
        value: ["Muito Favorável", "Favorável"],
      },
    ],
    sorting: [
      { field: "engagementScore", direction: "desc" },
      { field: "name", direction: "asc" },
    ],
    columns: [
      "name",
      "phone",
      "email",
      "city",
      "supportLevel",
      "engagementScore",
      "lastEngagementDate",
    ],
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-01-10"),
    createdBy: "user-1",
    isPublic: true,
    usageCount: 45,
    lastUsedAt: new Date("2026-01-12"),
  },
  {
    id: "2",
    name: "Voluntários Ativos",
    description: "Lista de todos os voluntários com status ativo",
    filters: [
      {
        id: "f1",
        field: "volunteerStatus",
        operator: "equals",
        value: "Ativo",
      },
    ],
    sorting: [{ field: "lastEngagementDate", direction: "desc" }],
    columns: [
      "name",
      "phone",
      "whatsapp",
      "email",
      "city",
      "volunteerStatus",
      "lastContactDate",
    ],
    createdAt: new Date("2026-01-03"),
    updatedAt: new Date("2026-01-03"),
    createdBy: "user-1",
    isPublic: false,
    usageCount: 23,
    lastUsedAt: new Date("2026-01-11"),
  },
  {
    id: "3",
    name: "Eleitores Jovens (18-35)",
    description: "Eleitores na faixa etária de 18 a 35 anos",
    filters: [
      {
        id: "f1",
        field: "ageGroup",
        operator: "in",
        value: ["18-24", "25-34"],
      },
    ],
    sorting: [{ field: "dateOfBirth", direction: "desc" }],
    columns: [
      "name",
      "dateOfBirth",
      "ageGroup",
      "city",
      "supportLevel",
      "instagram",
      "facebook",
    ],
    createdAt: new Date("2026-01-08"),
    updatedAt: new Date("2026-01-08"),
    createdBy: "user-2",
    isPublic: true,
    usageCount: 12,
    lastUsedAt: new Date("2026-01-10"),
  },
  {
    id: "4",
    name: "Alta Influência nas Redes",
    description: "Eleitores com alto score de influência e muitos seguidores",
    filters: [
      {
        id: "f1",
        field: "influencerScore",
        operator: "greaterThan",
        value: 80,
        logicalOperator: "AND",
      },
      {
        id: "f2",
        field: "socialMediaFollowers",
        operator: "greaterThan",
        value: 1000,
      },
    ],
    sorting: [
      { field: "influencerScore", direction: "desc" },
      { field: "socialMediaFollowers", direction: "desc" },
    ],
    columns: [
      "name",
      "phone",
      "influencerScore",
      "socialMediaFollowers",
      "instagram",
      "facebook",
      "twitter",
    ],
    createdAt: new Date("2026-01-06"),
    updatedAt: new Date("2026-01-09"),
    createdBy: "user-1",
    isPublic: true,
    usageCount: 34,
    lastUsedAt: new Date("2026-01-12"),
  },
  {
    id: "5",
    name: "Sem Contato Recente",
    description: "Eleitores que não tiveram contato nos últimos 90 dias",
    filters: [
      {
        id: "f1",
        field: "lastContactDate",
        operator: "lessThan",
        value: new Date("2025-10-13"), // 90 dias atrás
      },
    ],
    sorting: [{ field: "lastContactDate", direction: "asc" }],
    columns: [
      "name",
      "phone",
      "whatsapp",
      "city",
      "lastContactDate",
      "contactFrequency",
      "supportLevel",
    ],
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-01-10"),
    createdBy: "user-2",
    isPublic: false,
    usageCount: 8,
    lastUsedAt: new Date("2026-01-12"),
  },
  {
    id: "6",
    name: "Eleitores com Email Válido",
    description: "Lista para campanhas de email marketing",
    filters: [
      {
        id: "f1",
        field: "email",
        operator: "isNotEmpty",
        value: null,
        logicalOperator: "AND",
      },
      {
        id: "f2",
        field: "supportLevel",
        operator: "in",
        value: ["Muito Favorável", "Favorável", "Neutro"],
      },
    ],
    sorting: [{ field: "supportLevel", direction: "asc" }],
    columns: ["name", "email", "city", "supportLevel", "engagementScore"],
    createdAt: new Date("2026-01-04"),
    updatedAt: new Date("2026-01-07"),
    createdBy: "user-1",
    isPublic: true,
    usageCount: 67,
    lastUsedAt: new Date("2026-01-11"),
  },
  {
    id: "7",
    name: "Referenciadores Top",
    description: "Eleitores que mais referenciaram outros",
    filters: [
      {
        id: "f1",
        field: "referredVoters",
        operator: "greaterThan",
        value: 5,
      },
    ],
    sorting: [{ field: "referredVoters", direction: "desc" }],
    columns: [
      "name",
      "phone",
      "city",
      "referredVoters",
      "supportLevel",
      "engagementScore",
    ],
    createdAt: new Date("2026-01-07"),
    updatedAt: new Date("2026-01-07"),
    createdBy: "user-1",
    isPublic: false,
    usageCount: 19,
    lastUsedAt: new Date("2026-01-10"),
  },
];
